#!/usr/bin/env bash

if [[ $1 == "" ]];
then
	rng=$((1 + $RANDOM % 12 ))
else
	if [[ $1 -lt 13 ]];
	then
		rng=$1
	else
		rng=$((1 + $RANDOM % 12 ))
	fi
fi

uname -o &> /dev/null

if [ $(uname -s) == "Darwin" ]
then
        osname=$(sw_vers | cut -d':' -f2- | head -n 1 | xargs)
elif [ -f /etc/os-release ]
then
	osname=$(cat /etc/os-release | grep -w NAME | head -1 | sed 's/NAME=//g' | sed 's/\"//g' | sed 's/ Linux//g')
elif [ $? -eq 0 ]
then
	osname=$(uname -o)
else
	osname="Unknown"
fi

if [ $rng -eq 1 ]
then
        nofetch="probably a computer"
elif [ $rng -eq 2 ]
then
        nofetch="there's probably some ram in there"
elif [ $rng -eq 3 ]
then
        nofetch="init should ideally be running"
elif [ $rng -eq 4 ]
then
        nofetch="yeah"
elif [ $rng -eq 5 ]
then
        nofetch="you should probably go outside"
elif [ $rng -eq 6 ]
then
        nofetch="i would be lead to believe that / is mounted"
elif [ $rng -eq 7 ]
then
        nofetch="hey, what's this knob do ?"
elif [ $rng -eq 8 ]
then
        nofetch="do you have games on your phone ?"
elif [ $rng -eq 9 ]
then
        nofetch="you mean to tell me there aren't little men in this box?"
elif [ $rng -eq 10 ]
then
        nofetch="plan 4 from the front door"
elif [ $rng -eq 11 ]
then
	nofetch="i use "$osname" btw"
elif [ $rng -eq 12 ]
then
	nofetch="if you're reading this, it's already too late"
else
        nofetch="something has gone terribly wrong"
fi

osname=$(echo $osname | sed 's/FreeBSD //g')

echo " "
echo "> $nofetch" | tr '[:upper:]' '[:lower:]'
echo "> $osname $(uname -smr)" | tr '[:upper:]' '[:lower:]'
echo " "
