#!/usr/bin/env bash

echo " "
echo "+------------------------+"
echo "|                        |"
echo "|   probably a computer  |"
echo "|                        |"
echo "+------------------------+"
echo " "
